src/Entity/Experience.php
<?php

namespace App\Entity;

use App\Repository\ExperienceRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ExperienceRepository::class)
 */
class Experience
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", name="id_user_experiences")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Function;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Place;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $context;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $realisations;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $technical_environment;

    /**
     * @ORM\Column(type="date")
     */
    private $start_date;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $end_date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\ManyToOne(targetEntity=TypeExperience::class, inversedBy="experiences")
     */
    private $type_experience;

    /**
     * @ORM\ManyToOne(targetEntity=Entreprise::class, inversedBy="experiences")
     */
    private $entreprise;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="experiences")
     */
    private $user;


    public function __construct()
    {
        $this->experiences = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFunction(): ?string
    {
        return $this->Function;
    }

    public function setFunction(string $Function): self
    {
        $this->Function = $Function;

        return $this;
    }

    public function getPlace(): ?string
    {
        return $this->Place;
    }

    public function setPlace(string $Place): self
    {
        $this->Place = $Place;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getContext(): ?string
    {
        return $this->context;
    }

    public function setContext(string $context): self
    {
        $this->context = $context;

        return $this;
    }

    public function getRealisations(): ?string
    {
        return $this->realisations;
    }

    public function setRealisations(string $realisations): self
    {
        $this->realisations = $realisations;

        return $this;
    }

    public function getTechnicalEnvironment(): ?string
    {
        return $this->technical_environment;
    }

    public function setTechnicalEnvironment(string $technical_environment): self
    {
        $this->technical_environment = $technical_environment;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(?\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getTypeExperience(): ?TypeExperience
    {
        return $this->type_experience;
    }

    public function setTypeExperience(?TypeExperience $type_experience): self
    {
        $this->type_experience = $type_experience;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }


    public function __toString()
    {
        return $this->name;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
//use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints\DateTime;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @Vich\Uploadable()
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string", nullable=true)
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstname;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastname;

    /**
     * @ORM\Column(type="smallint")
     */
    private $age;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $profession;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=10)
     */
    private $postalcode;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $Collab;


    /**
     * @ORM\OneToMany(targetEntity=Experience::class, mappedBy="user")
     */
    private $experiences;

    /**
     * @ORM\OneToMany(targetEntity=Competences::class, mappedBy="user")
     */
    private $competences;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $available;


    public function __construct()
    {
        $this->competences = new ArrayCollection();
        $this->experiences = new ArrayCollection();
//        $this->updatedAt = new DateTime();

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getUsername()
    {
        // TODO: Implement getUsername() method.
    }

    public function getFirstname(): ?string
    {
        return $this->firstname;
    }

    public function setFirstname(string $firstname): self
    {
        $this->firstname = $firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->lastname;
    }

    public function setLastname(string $lastname): self
    {
        $this->lastname = $lastname;

        return $this;
    }

//    public function getCompetences(): Collection
//    {
//        return $this->competences;
//    }
//
//    public function setCompetences(?Competences $competences): self
//    {
//        $this->competences = $competences;
//
//        return $this;
//    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getProfession(): ?string
    {
        return $this->profession;
    }

    public function setProfession(string $profession): self
    {
        $this->profession = $profession;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): self
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getPostalcode(): ?string
    {
        return $this->postalcode;
    }

    public function setPostalcode(string $postalcode): self
    {
        $this->postalcode = $postalcode;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCollab(): ?bool
    {
        return $this->Collab;
    }

    public function setCollab(?bool $Collab): self
    {
        $this->Collab = $Collab;

        return $this;
    }
    public function __toString()
    {
        return $this->firstname;
    }

    /**
     * @return Collection|Competences[]
     */
    public function getCompetences(): Collection
    {
        return $this->competences;
    }

    public function addCompetence(Competences $competence): self
    {
        if (!$this->competences->contains($competence)) {
            $this->competences[] = $competence;
        }

        return $this;
    }

    public function removeCompetence(Competences $competence): self
    {
        $this->competences->removeElement($competence);

        return $this;
    }

    /**
     * @return Collection|Experience[]
     */
    public function getExperiences(): Collection
    {
        return $this->experiences;
    }

    public function addExperience(Experience $experience): self
    {
        if (!$this->experiences->contains($experience)) {
            $this->experiences[] = $experience;
            $experience->setUser($this);
        }

        return $this;
    }

    public function removeExperience(Experience $experience): self
    {
        if ($this->experiences->removeElement($experience)) {
            // set the owning side to null (unless already changed)
            if ($experience->getUser() === $this) {
                $experience->setUser(null);
            }
        }

        return $this;
    }

//    public function getUpdatedAt(): ?\DateTimeInterface
//    {
//        return $this->updatedAt;
//    }
//
//    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
//    {
//        $this->updatedAt = $updatedAt;
//
//        return $this;
//    }

//    public function getFile(): ?File
//    {
//        return $this->file;
//    }
//
//    public function setFile(?File $file): self
//    {
//        // unset the owning side of the relation if necessary
//        if ($file === null && $this->file !== null) {
//            $this->file->setUser(null);
//        }
//
//        // set the owning side of the relation if necessary
//        if ($file !== null && $file->getUser() !== $this) {
//            $file->setUser($this);
//        }
//
//        $this->file = $file;
//
//        return $this;
//    }

public function getAvailable(): ?bool
{
    return $this->available;
}

public function setAvailable(?bool $available): self
{
    $this->available = $available;

    return $this;
}




}

src/Controller/ProfilController.php
<?php

namespace App\Controller;

use App\Entity\Competences;
use App\Entity\User;
use App\Form\CompetencesType;
use App\Form\UserEditType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProfilController extends AbstractController
{
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
    /**
     * @Route("/profil", name="admin-profil")
     */
    public function index(): Response
    {
        return $this->render('profil/index.html.twig', [
            'controller_name' => 'ProfilController',
        ]);
    }



}

templates/profil/edit.html.twig
{% block page_content %}
    <div class="container">
        {{ form_start(edit_user) }}
            {{ form_row(edit_user.firstname) }}
        {{ form_end(edit_user) }}
    </div>
{% endblock %}

templates/profil/index.html.twig
{% extends '@EasyAdmin/page/content.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block page_content %}
    <div class="container-page-details">
        <div class="profil-main-info">
            <div class="status">
                {% if app.user.collab == 1 %}
                    <p>Collaborateur</p>
                {% endif %}
                {% if app.user.collab == null %}
                    <p>Candidat</p>
                {% endif %}
            </div>
            <h2 class="title">Profil</h2>
            <div class="name">
                <p>{{ app.user.lastname }}</p>
                <p>{{ app.user.firstname }}</p>
            </div>
            <div class="profession">
                <p>{{ app.user.profession }}</p>
            </div>
            <div class="adresse">
                <h3>Adresse</h3>
                <p>{{ app.user.adresse }}</p>
            </div>
            <div class="cp">
                <h3>Code postal</h3>
                <p>{{ app.user.postalcode }}</p>
            </div>
            <div class="city">
                <h3>Ville</h3>
                <p>{{ app.user.city }}</p>
            </div>
            <div class="email">
                <h3>Email</h3>
                <p>{{ app.user.email }}</p>
            </div>
            <div class="competences">
                <h3>Compétences principales</h3>
                {% for competence in app.user.competences %}
                    <p class="single-competence">{{ competence.name }}</p>
                {% endfor %}
            </div>
            <a class="edit-competence" href="{{ path('edit-user', { 'id': app.user.id})}}">Editer mon profil</a>
        </div>
        <div class="competences-part">
            <div class="form-skills">
                <h2>Mes Compétences</h2>
                <a href="{{ path('new-competence', { 'id': app.user.id})}}">Ajouter une compétence</a>
            </div>
            <div class="competences-all">
                {% for competence in app.user.competences %}
                    <div class="single-competence-container">
                        <p class="single-competence">{{ competence.name }}</p>
                        {% if competence.competencelike == 1 %}
                            <i class="fa fa-heart"></i>
                        {% endif %}
                        {% if competence.competencelike == null %}
                        {% endif %}
                        {% if competence.levelcompetence == null %}
                        {% else %}
                            <p> niveau: {{ competence.levelcompetence }} </p>
                        {% endif %}
                        <a class="edit-competence" href="{{ path('admin_competences_edit', { 'user': app.user.id, 'id': competence.id})}}">Editer</a>

                    </div>

                {% endfor %}
            </div>
        </div>
        <div class="experience-part">
            <div class="form-experience">
                <h2>Mes Expériences</h2>
                <a href="{{ path('new_experience', { 'id': app.user.id})}}">Ajouter une expérience</a>
            </div>
            <div class="competences-all">
                {% for experience in app.user.experiences %}
                    <div class="competence-single">
                        <h3>Experience</h3>
                        <span>{{ experience.startdate|date("m/d/Y")}} - {{ experience.enddate|date("m/d/Y")}}</span>
                        <p class="single-competence">{{ experience.function }}</p>
                        <p>{{ experience.place}}</p>
                        <p>{{ experience.description }}</p>
                        <a class="edit-competence" href="{{ path('admin_experience_edit', { 'user': app.user.id, 'id': experience.id})}}">Editer</a>

                    </div>

                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}

templates/profil/new.html.twig
{% block page_content %}
<div class="container">
        {{ form(articleForm) }}
</div>
{% endblock %}

templates/profil/profil.html.twig
{% extends '@EasyAdmin/page/content.html.twig' %}

{% block title %}Mon profil{% endblock %}

{% block page_content %}
<div class="container-page-details">
    <div class="profil-main-info">
        <div class="status">
            {% if user.collab == 1 %}
                <p>Collaborateur</p>
            {% endif %}
            {% if user.collab == null %}
                <p>Candidat</p>
            {% endif %}
            {% if user.available == 1 %}
                <p>Disponible</p>
            {% endif %}
            {% if user.available == 0  %}
                <p>Pas disponible</p>
            {% endif %}
            {% for competence in user.competences %}

            {% endfor %}
        </div>
        <h2 class="title">Profil</h2>
        <div class="name">
            <p>{{ user.lastname }}</p>
            <p>{{ user.firstname }}</p>
        </div>
        <div class="profession">
            <p>{{ user.profession }}</p>
        </div>
        <div class="adresse">
            <h3>Adresse</h3>
            <p>{{ user.adresse }}</p>
        </div>
        <div class="cp">
            <h3>Code postal</h3>
            <p>{{ user.postalcode }}</p>
        </div>
        <div class="city">
            <h3>Ville</h3>
            <p>{{ user.city }}</p>
        </div>
        <div class="email">
            <h3>Email</h3>
            <p>{{ user.email }}</p>
        </div>
        <div class="competences">
            <h3>Compétences principales</h3>
            {% for competence in user.competences %}
                <p class="single-competence">{{ competence.name }}</p>
            {% endfor %}
        </div>
    </div>
    <div class="competences-part">
        <div class="form-skills">
            <h2>Compétences</h2>
            {{ form(form_competences) }}
        </div>
        <div class="competences-all">
            {% for competence in user.competences %}
                <div class="single-competence-container">
                    <p class="single-competence">{{ competence.name }}</p>
                    {% if competence.competencelike == 1 %}
                        <i class="fa fa-heart"></i>
                    {% endif %}
                    {% if competence.competencelike == null %}
                    {% endif %}
                   {% if competence.levelcompetence == null %}
                       {% else %}
                           <p> niveau: {{ competence.levelcompetence }} </p>
                   {% endif %}
                    <a class="edit-competence" href="{{ path('admin_competences_edit', { 'user': user.id, 'id': competence.id})}}">Editer</a>

                </div>

            {% endfor %}
        </div>
    </div>
    <div class="experience-part">
        <div class="form-experience">
            <h2>Expériences</h2>
            {{ form(form_experiences) }}
        </div>
        <div class="competences-all">
            {% for experience in user.experiences %}
                <div class="competence-single">
                    <h3>Experience</h3>
                    <span>{{ experience.startdate|date("m/d/Y")}} - {{ experience.enddate|date("m/d/Y")}}</span>
                    <p class="single-competence">{{ experience.function }}</p>
                    <p>{{ experience.place}}</p>
                    <p>{{ experience.description }}</p>
                    <a class="edit-competence" href="{{ path('admin_experience_edit', { 'user': user.id, 'id': experience.id})}}">Editer</a>

                </div>

            {% endfor %}
        </div>
    </div>
</div>
    <div class="edit">

    </div>
{% endblock %}